// Cross-platform entry point for saving generated bytes.
//
// On web this resolves to a real browser download; off web it resolves to a
// stub that throws, since native platforms save/share through other APIs
// (callers guard with `kIsWeb`).
export 'file_download_stub.dart'
    if (dart.library.js_interop) 'file_download_web.dart';
